server:
  port: 9001

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: test-alipay

alipay:
  appId: 9021000134675287
  ## java私钥
  appPrivateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCS9x4fMh2Kp4xiUDfO8uRCuQOCJsLD1gj0vpImrtbTT+y7SZLL2pzMv/aKoac2zw+tF520GFKhKHif8FLPJTavF13rIeku9GvNZGtJ4yeiIQAVy7ZUfAZv5GdLqob2CeNHmok5/esBgJAEPGXgss6Yw6eD4xb2B83tq8txDYF2roZtyyw9o9Q/WXy/NTDXatXyNuvGycMOEVroZYf4EX/ool012a8vVD4+rV1f+6wG9hhQ930Q+73uYTMIHHqD82lSO6qzr1GnLnGnTNmm0h0Ze//CYmHN1dU6ntFHUjW0rBeTWZQyHxNAJ6Ty5KjsK6VFfABbink/zthcNDsF71pLAgMBAAECggEATDw8N9p7UI2RWP5btNJybdojY8RPi97fTnX8wmw3q+3t00lbCLwiUmPRtCAe6WOHsjZp7B4h3s9royu7CRE4yKLKaUpx95V6xlStAur+iC+uJ6BAuJqNjEVi//E5iS+f4mjbfmWlHmZeTpQ2FNUsLjpwDw4hvwZVYFCZe8+RtMoSUv+KsX6h6lgTVTLDC40IhzEv1I2KDqoIlMf+HwjLI26AwamMh+CYj7MfWz5xB7IBXopR3MxhhfYDeJH5bjSqQCuUGOPRmgNra3u5lC6aIc3qZOeu21UC9Fz10kwFEvyn8BSc2kdxngfGx3SQ+vROkygbPyx43ByvdU8r8i1wAQKBgQDF4ki3Kx35RI6iP8BgM9atb/CUrhQuZaMELh1mqN2X2WJZb4WGJztXPTtPTkXmPz0NXF9n0brJ4TXS1jm73yYjplQQYuDO+MuB7f9IYs2koiRMHcLBwAE32U1nb/IPEH/I2vT3YdpnXLAnKYLcnPs49jgaCib8afc8A8Sa1CjyAQKBgQC+IJC41lSsA2wUYZcmvPCwn/Yaz5hIgpFn0Le8xa11kTXsN/0fpzgTEhrceM0lAd0uIgToZzzelmeynfrTm1P4fqYeCDcaRHFLHqrQjQ9bZWuM02LXqkfufHU2CdhHa67M8+DTR/AAZcKyp7YiVszUtrYZ5A0Caxx4k5q4QEh0SwKBgQCz1XSt+eJQkWxqqTNEenfjwLJL/HPcwoNGnj4b+OUBRg6qJr6a73ZvTvdimEjP+bKbPNJ7gE+XfjMy+3sWcLKxfUwyZBnYHqSb3NW+TASFVNFV10oSWFMDFVnR4huCc0UeHVa4p1Ybz1FLFd+WbJem6aSMjaNmi0qjYO1ApATeAQKBgG+WLVpOcOOEHqrXnB7gRWNkfsy9imMEPtLvbOceHfAiicNaGPW67u5CcgFz5PMTZPzuenLsJI1/ON1cWxpWz7HIozZ9G9oO0W+FUDuWjqzVmYnNhvWMuyr9YM2WeZlxWeZwPEPEtNeG4f548Cy3RQCTO812SyxgMRWTi/sXv26BAoGAJzVgqXx/iaT8t75VkTLhiaGAWWjoceXSm/U7dtBlHWnc4iH+8REJbb8BtxqFQJhswq2wXV118C3hXBPNxTF7OOEXyXebiMjl0vq1jHtbKAP7TIgysuj1i6f1beeNsvv6wFJf3/5T8MKeVHKUmx0y17IvYRi8yDugrp7QNBgRKkU=
  ## 支付宝公钥
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqEhaO0atMTH78cSbHyiOjd91kB8N+Hb7nlgwGl/63ZS7M8k/77EHZj9DNNdXQjvXYA2k9WYu0pSbYeN5aLXae9a6G0eyPTsvBuIz9A467NtcObOByUrdCmyJRSGZR8InOkwSKkkmNe0lEvHHj1VybUbczIerITn/w2ZnguyfLwGSAz/fzb4KLF6GLmMnfOuVo97ELLJu1x4zrugfjXJ27RsmK1ReL+EnDeMTrPbeIpkIOuQZ6iIjOg4WASdu0CNxJsAtDEeC5cKN8pHexGAhRuYg1CTJDoohtQDBqxAxPMj15ncPanhH78gqkIffKx74qYOzQqSyOPlyuz9A/+AzVwIDAQAB
  ## 回调地址
  notifyUrl: https://8751f653m0.goho.co/test

