#server:
#  port: 8089

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  application:
    name: service-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    ## Mysql8\u4EE5\u4E0A\u8981\u52A0serverTimezone=GMT%2B8
    url: jdbc:mysql://localhost:3306/service-order?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

logging:
  level:
    com.baomidou.mybatisplus: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---

spring:
  profiles: 8089
server:
  port: 8089
---
spring:
  profiles: 8090
server:
  port: 8090